import "@/lib/loadEnv";

export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";

interface CreatePRRequest {
  repo: string;
  branchName: string;
  baseBranch: string;
  title: string;
  body: string;
}

export async function POST(request: NextRequest) {
  try {
    const requestData: CreatePRRequest = await request.json();
    const { repo, branchName, baseBranch, title, body } = requestData;

    // Validate required fields
    if (!repo || !branchName || !baseBranch || !title) {
      return NextResponse.json(
        { error: "Missing required fields: repo, branchName, baseBranch, and title are required" },
        { status: 400 }
      );
    }

    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      return NextResponse.json(
        { error: "GITHUB_TOKEN environment variable is not set" },
        { status: 500 }
      );
    }

    // Validate repo format (owner/repo)
    const repoParts = repo.split("/");
    if (repoParts.length !== 2 || !repoParts[0] || !repoParts[1]) {
      return NextResponse.json(
        { error: "Invalid repository format. Use owner/repo (e.g., vercel/next.js)" },
        { status: 400 }
      );
    }

    const [owner, repoName] = repoParts;

    // Create pull request via GitHub API
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/pulls`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
          "User-Agent": "BugSmith",
        },
        body: JSON.stringify({
          title,
          body: body || "This PR was generated by BugSmith's autonomous agent.",
          head: branchName,
          base: baseBranch,
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: "Unknown error" }));
      
      if (response.status === 422) {
        // Unprocessable entity - usually means branch doesn't exist or PR already exists
        const errorMessage = errorData.message || errorData.errors?.[0]?.message || "Failed to create PR";
        return NextResponse.json(
          { error: `Cannot create PR: ${errorMessage}` },
          { status: 422 }
        );
      }
      
      if (response.status === 404) {
        return NextResponse.json(
          { error: "Repository or branch not found. Please check the repository and branch names." },
          { status: 404 }
        );
      }
      
      if (response.status === 401 || response.status === 403) {
        return NextResponse.json(
          { error: "GitHub authentication failed. Please check your GITHUB_TOKEN." },
          { status: 401 }
        );
      }

      return NextResponse.json(
        { error: errorData.message || `GitHub API error: ${response.statusText}` },
        { status: response.status }
      );
    }

    const prData = await response.json();

    // Return simplified PR data
    return NextResponse.json({
      number: prData.number,
      title: prData.title,
      state: prData.state,
      html_url: prData.html_url,
      created_at: prData.created_at,
      user: prData.user?.login,
    });
  } catch (error) {
    console.error("Error creating GitHub PR:", error);
    return NextResponse.json(
      { error: "Failed to create pull request. Please try again later." },
      { status: 500 }
    );
  }
}

